### ISSUE TITLE
centos7 下无法执行 ansible-playbook -i inventories/my_inventory/hosts.ini fisco_bcos.yml

### ISSUE THREAD

**Issue by wcmolin** [newtouch-cloud/ansible-for-fisco-bcos#1]
ansible 版本 ：
```
[root@peer0 ansible-for-fisco-bcos-master]# ansible --version
ansible 2.9.15
  config file = /root/fisco/ansible-for-fisco-bcos-master/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```
linux 版本：
```
[root@peer0 ansible-for-fisco-bcos-master]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
```

执行命令：
```
[root@peer0 ansible-for-fisco-bcos-master]# ansible-playbook -i inventories/my_inventory/hosts.ini fisco_bcos.yml
```
报错：
```
TASK [fisco_bcos : 设置动态变量] ******************************************************************************
Monday 23 November 2020  21:06:00 +0800 (0:00:00.049)       0:00:02.387 *******
ok: [localhost]

TASK [fisco_bcos : 检查每个群组是否有且只有 1 个创世区块机构] **************************************************************
Monday 23 November 2020  21:06:00 +0800 (0:00:00.069)       0:00:02.456 *******
fatal: [localhost]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: set([1, 2]). Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}
```

难道是ansible版本要升级到 ```2.10.1``` ? 我查了下ansible 在 centos上目前只能用到 ```2.9.*```

**Comment by bottlelee** [comment]
你好，抱歉回复晚了。你可以自行升级 ansible。按以下命令试试：

> pip install -U ansible

**Comment by bottlelee** [comment]
> ansible 版本 ：
> 
> ```
> [root@peer0 ansible-for-fisco-bcos-master]# ansible --version
> ansible 2.9.15
>   config file = /root/fisco/ansible-for-fisco-bcos-master/ansible.cfg
>   configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
>   ansible python module location = /usr/lib/python2.7/site-packages/ansible
>   executable location = /usr/bin/ansible
>   python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
> ```
> 
> linux 版本：
> 
> ```
> [root@peer0 ansible-for-fisco-bcos-master]# cat /etc/redhat-release
> CentOS Linux release 7.4.1708 (Core)
> ```
> 
> 执行命令：
> 
> ```
> [root@peer0 ansible-for-fisco-bcos-master]# ansible-playbook -i inventories/my_inventory/hosts.ini fisco_bcos.yml
> ```
> 
> 报错：
> 
> ```
> TASK [fisco_bcos : 设置动态变量] ******************************************************************************
> Monday 23 November 2020  21:06:00 +0800 (0:00:00.049)       0:00:02.387 *******
> ok: [localhost]
> 
> TASK [fisco_bcos : 检查每个群组是否有且只有 1 个创世区块机构] **************************************************************
> Monday 23 November 2020  21:06:00 +0800 (0:00:00.069)       0:00:02.456 *******
> fatal: [localhost]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: set([1, 2]). Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}
> ```
> 
> 难道是ansible版本要升级到 `2.10.1` ? 我查了下ansible 在 centos上目前只能用到 `2.9.*`

另外，麻烦你把 init.yml 的配置内容贴一下，谢谢。

**Comment by wcmolin** [comment]
@bottlelee  感谢回复！
我通过 `pip install -U ansible` 升级 `ansible` 到 `2.10.3` 版本之后，可以成功运行。

`init.yml ` 我并未改动，就是 clone 下来的原本配置。
```
agencies:
  - name: A
    create_genesis: true
    nodes:
      - 172.17.8.101:2
    main_group_id: 1
    extra_group_id:
      - 2
  - name: B
    nodes:
      - 172.17.8.103:2
    main_group_id: 1
  - name: C
    create_genesis: true
    nodes:
      - 172.17.8.105:2
    main_group_id: 2

# 是否使用国密版
fisco_gm_enabled: false

# 是否生成控制台
fisco_console_enabled: false

# 是否生成 SDK
fisco_sdk_enabled: false
```
